#!/bin/sh

#--------------------------
# make the git repo accessible via:
#   git clone http://blah-blah
#--------------------------

cd `dirname $0`

git update-server-info
# rsync -av --exclude /weather --exclude /maps . host:dir